version: '3.7'

services:
  flaskapp:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - INFLUXDB_URL=http://localhost:8086
      - INFLUXDB_TOKEN=PLHVTO5-hxRlXKPPOVhwmt2BMH21knPYk5jhxS5aBmFQosilbYVD-DAmmVNkAswMWu-NTlu-uQ3gmIUrhGemtQ==
      - INFLUXDB_ORG=FuelLink
      - PYTHONUNBUFFERED=1 
    volumes:
      - ./app:/app