apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: influxdb
  name: influxdb
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/market-analysis-default: "true"
        io.kompose.service: influxdb
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: INFLUXDB_ADMIN_PASSWORD
              value: admin123
            - name: INFLUXDB_ADMIN_USER
              value: admin
            - name: INFLUXDB_DB
              value: mydb
            - name: INFLUXDB_HTTP_AUTH_ENABLED
              value: "true"
          image: influxdb:latest
          name: influxdb
          ports:
            - containerPort: 8086
              hostPort: 50124
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-storage
      restartPolicy: Always
      volumes:
        - name: influxdb-storage
          persistentVolumeClaim:
            claimName: influxdb-storage
