apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: market-analysis
  name: market-analysis
  namespace: egs-fuellink
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: market-analysis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/market-analysis-default: "true"
        io.kompose.service: market-analysis
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: PYTHONUNBUFFERED
              value: "1"
          image: registry.deti/egs-fuellink/analysis:v1
          imagePullPolicy: Always
          name: market-analysis
          ports:
            - containerPort: 5000
              hostPort: 50123
              protocol: TCP
          volumeMounts:
            - mountPath: /app
              name: market-analysis-cm0
            - mountPath: /app/data
              name: analysis-db
      restartPolicy: Always
      volumes:
        - configMap:
            name: market-analysis-cm0
          name: market-analysis-cm0
        - name: analysis-db
          persistentVolumeClaim:
            claimName: analysis-db
